<?php
/**
 * Copyright © Karliuka Vitalii(karliuka.vitalii@gmail.com)
 * See COPYING.txt for license details.
 */
?>
<?php if (!$this->isShowDecimalZero()): ?>
<script>
    Product.Config.addMethods({
        formatPrice: function(price, showSign){
            var str = '';
            price = parseFloat(price);
            if(showSign){
                if(price<0){
                    str+= '-';
                    price = -price;
                }
                else{
                    str+= '+';
                }
            }

            var roundedPrice = (Math.round(price*100)/100).toString();

            if (this.prices && this.prices[roundedPrice]) {
                str+= this.prices[roundedPrice];
            }
            else {
                var precision = (parseInt(price) == price) ? 0 : 2;
                str+= this.priceTemplate.evaluate({price:price.toFixed(precision)});
            }
            return str;
        }
    });
</script>
<?php endif ?>